meetfactory/urls.py
from django.conf.urls import patterns, url

from meetfactory import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^json/$', views.jsons, name='json'),
    url(r'^vk_login/$', views.vk_login, name='vk_login'),
    url(r'^event_create/$', views.event_create, name='event_create'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^events/add/$', views.subscribe_event, name='add'),
    url(r'^events/$', views.event)
)

proj/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'proj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('meetfactory.urls', namespace='meetfactory')),

)

meetfactory/models.py
# -*- coding: <utf-8> -*-

from django.db import models
from django.forms import ModelForm
from django import forms
from datetime import *
from django.db.models import (ManyToManyField, CharField, IntegerField,
        ForeignKey, DateTimeField, FloatField, TextField, Model)

class SerializableModel(Model):
    class Meta:
        abstract = True

    def serialize(self):
        def getf(f):
            if hasattr(f, '__iter__'):
                f = list(f)
            else:
                f = (f, f,)
            return (f[0], getattr(self, f[1]))
        if hasattr(self, 'serializable_fields'):
            fields = self.serializable_fields
            return dict(map(getf, fields))
        elif hasattr(self, '__unicode__'):
            return self.__unicode()

class User(SerializableModel):
        vk_id = CharField(max_length=100)
        access_token = CharField(max_length=200)
        expires_in = IntegerField(max_length=200)
        first_name = CharField(max_length=200)
        last_name = CharField(max_length=200)
        userpic = CharField(max_length=200)

        serializable_fields = [
            'first_name', 'last_name', 'vk_id',
            ('url_pic', 'userpic',),]

        def __unicode__(self):
            return self.vk_id

class Category(SerializableModel):
        name = CharField(max_length=100)

        def __unicode__(self):
            return unicode(self.name)

class Tag(SerializableModel):
        name = CharField(max_length=10)

        def __unicode__(self):
            return self.name

class Event(SerializableModel):
        name = CharField(max_length=100)
        low_people_count = IntegerField(default=0)
        high_people_count = IntegerField(default=0)
        creator = ForeignKey(User, related_name='created_events')
        begin_date = DateTimeField()
        end_date = DateTimeField()
        money = FloatField(blank=True, default=0)
        desc = TextField()
        location = TextField(blank=True)
        category = ForeignKey(Category, blank=True, default=1)

        tags = ManyToManyField(Tag, through='EventTag')
        users = ManyToManyField(User, through='EventUser')

        serializable_fields = [
            'id', 'name', 'creator',
            'low_people_count',
            'high_people_count',
            'begin_date', 'end_date',
            'money', 'desc', 'location',]          

        def __unicode__(self):
            return self.name

class EventForm(ModelForm):
        begin_date = forms.DateField(widget=forms.DateInput, input_formats=['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y'], initial=date.today)

        class Meta:
            model = Event
            fields = "__all__"

class EventUser(SerializableModel):
        user = ForeignKey(User)
        event = ForeignKey(Event)

        def __unicode__(self):
            return self.user.vk_id + " " + self.event.name

class EventTag(SerializableModel):
        event = ForeignKey(Event)
        tag = ForeignKey(Tag)

        def __unicode__(self):
            return self.event.name + " " + self.tag.name

meetfactory/views.py
import json, datetime, socket
from urllib import urlencode
from httplib2 import Http

from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, HttpResponse, redirect
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.db.models import Q

from meetfactory.models import *
from auth import vk
from proj.decorators import ajax
from auth.decorators import login_required

def index(request):
    events = Event.objects.all()
    q = request.GET.get('q')
    _get = request.GET.get
    G = {f+'q': _get(f+'q') == 'on' for f in 'tdnl'}
    if q:
        N = Q(id=0)
        qtags = Tag.objects.filter(name__contains=q)
        e_tags = Q(tags__in=qtags) if G['tq'] else N
        d_tags = Q(desc__contains=q) if G['dq'] else N
        n_tags = Q(name__contains=q) if G['nq'] else N
        l_tags = Q(location__contains=q) if G['lq'] else N
        events = events.filter(
                e_tags | d_tags | n_tags | l_tags)
    cat = request.GET.get('category')
    if cat:
        events = events.filter(category=cat)
    cs = Category.objects.all()
    need_to_login = request.vk_user is None
    return render(request, 'meets/index.html',
            {'el':events, 'need_to_login':need_to_login,
                'categories':cs, 'cat': cat, 'G': G,'q':q,})


def event(request):
    e = get_object_or_404(Event, pk=request.GET.get('id'))
    tags = ['#' + unicode(t) for t in e.tags.all()]
    u = request.vk_user
    user_in = u is not None and e.users.filter(user=u)
    return render(request, 'meets/event_profile.html', 
            {'e': e,'tags': ' '.join(tags)})

@login_required
def event_create(request):
    if request.method == 'POST':
        access_token = request.COOKIES['access_token']
        creator = User.objects.filter(access_token=access_token)[0]
        event =  Event(creator=creator)
        form = EventForm(request.POST, instance=event)
        event = form.instance
        tags = request.POST['tags_event']
        location_count = request.POST['location_count']
        location = ""
        for i in xrange(int(location_count)+1):
            location += request.POST['location' + str(i)] + " "
        event.location = location
        event.save()
        tags = tags.split()
        for tg in tags:
            tag = Tag(name=tg)
            tag.save()
            EventTag(event=event, tag=tag).save()

        return HttpResponseRedirect('/')
    else:
        form = EventForm()

    return render(request, 'meets/event.html', {
        'form': form, 'need_to_login':need_to_login}
    )

@login_required
def subscribe_event(request):
    e = Event.objects.filter(pk=request.POST.get('id'))
    EventUser.objects.get_or_create(user=request.user, event=e)
    return HttpResponseRedirect('/events/?id=' + e.pk)

def profile(request):
    need_to_login = not request.COOKIES.has_key('access_token')
    access_token = request.COOKIES['access_token']
    creator = User.objects.filter(access_token=access_token)[0]

    return render(request, 'meets/profile.html',
        {'u': creator, 'need_to_login':need_to_login}
    )

@csrf_exempt
@ajax
def jsons(request):
    E_NO_EVENT = {'error':'no_event',}
    E_OK = {'result': 'OK',}

    if settings.AJAX_DEBUG and not request.is_ajax():
        input = request.REQUEST
    else:
        input = json.loads(request.body)

    action = input.get('action')
    
    user = request.vk_user
    print user

    if 'oauth_vk' in request:
        return user


    if 'last_events' in action:
        offset = int(input['offset'])
        events = Event.objects.all()[offset:offset+20]
        return events

    if 'open_event' in action:
        id = int(input['id'])
        e = list(Event.objects.filter(pk=id))
        return e[0] if e else E_NO_EVENT

    if 'subscribe_event' in action:
        user = get_object_or_404(User, pk=1)
        id = int(input.get('id', 0))
        event = list(Event.objects.filter(pk=id))
        if not event:
            return E_NO_EVENT

        ev_us = Event.objects.get_or_create(user=user, event=event)
        
        return E_OK

    if 'cancel_event' in action:
        id = int(input['id'])
        EventUser.objects.filter(user=user, event__id=id).delete()

        return E_OK

def vk_login(request):
    VK_LINK = 'https://oauth.vk.com/access_token'
    response = redirect('/')

    if request.vk_user is not None:
        return response

    code = request.REQUEST.get('code')
    if not code:
        return response

    get = dict(
            client_id=settings.VK_APP_ID,
            client_secret=settings.VK_APP_SECRET,
            code=code,
            redirect_uri='http://%s/vk_login/' % request.get_host())
    print get

    link = VK_LINK + '?' + urlencode(get)
    print link
    resp, c = Http().request(link)

    dat = json.loads(c)
    user_id = dat['user_id']
    print user_id
    access_token = dat['access_token']
    expires_in = dat['expires_in']

    get = dict (
            user_id = user_id,
            fields = "photo_50",
            access_token = access_token
        )

    dat = vk.api('users.get', **get)['response'][0]

    fname = dat['first_name'].encode('utf-8')
    lname = dat['last_name'].encode('utf-8')
    photo = dat['photo_50'].encode('utf-8')

    response.set_cookie('fistname', fname, expires=expires_in)
    response.set_cookie('lastname', lname, expires=expires_in)
    response.set_cookie('access_token', access_token, expires=expires_in)


    User(
        vk_id = user_id,
        access_token = access_token,
        expires_in = expires_in,
        first_name = fname,
        last_name = lname,
        userpic = photo).save()

    return response

meetfactory/templates/meets/event.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}

    <!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
	<script type="text/javascript" src="http://maps.api.2gis.ru/1.0">
	 </script>
	
<div class = "wrapper">
	<div class = "head_title"><h3>Meet Factory</h3></div>
	<div class = "create_event">
		<div class = "create_head">
			Создание мероприятия
		</div>
		<div class = "create_form">
			<form id=event_form action="{% url 'meetfactory:event_create' %}" method="post"> {% csrf_token %}
				<label for = "name">Название мероприятия</label>
				<input type = "text" class = "name" name = "name" value = "" />
				<br />
				<br />
				<label for = "number_event">Количество участников</label>
				<input type = "text" class = "number" name = "low_people_count" placeholder = "Min" />
				<input type = "text" class = "number" name = "high_people_count" placeholder = "Max" />
				<br />
				<br />
				<label for = "begin_date">Дата/время начала</label>
				<input type = "datetime" name = "begin_date" />
				<br />
				<br />
				<label for = "end_date">Дата/время завершения</label>
				<input type = "datetime" name = "end_date"/>
				<br />
				<br />
				<label for = "money">Предположительные затраты</label>
				<input type = "text" name = "money" value = "" />
				<br />
				<br />
				<label for = "tags_event">Тэги</label>
				<input type = "text" name = "tags_event" value = "" />
				<br />
				<br />
				<label for = "reject_event">Возможен ли отказ от мероприятия</label>
				<input type = "checkbox" />
				<br />
				<br />
				<label for = "category">Категория</label>
                    {% for field in form %}
                    {% if field.name == "category"%}
                            {{ field }}
                    {% endif %}
                    {% endfor %}
				<br />
				<br />
	<div class = "map_event">
	    	<div id="map" style="width: 400px; height: 300px"></div>
	    	<br />
	    	<div class = "map_inputs">
	    		<input type = "text" class = "geo_info" class = "geo_info" placeholder = "Введите местоположение" />
	    		<button id = "geo">Найти</button>
	    		<br />
	    		<br />
	    		<label for = "desc">Описание события</label>
	    		<br />
	    		<textarea class = "description" name = "desc"></textarea>
	    	</div>
    		<div class = "list">
    			<p>Список точек</p>
				<ul>
				</ul>
			</div>
	</div>
                <input id="cnt" name="location_count" type="text" value="0"/>
               <input type = "submit" value = "Submit" />
                </form>
        </div>
    </div>
</div>
<footer><a href="profile.html">Профиль</a><a class = "create_footer" href="index.html">Создать событие</a></footer>
<script type="text/javascript" src = "{% static 'meets/js/functions.js' %}"></script>
<script type="text/javascript" src = "{% static 'meets/js/map.js' %}"></script>

{% endblock %}

meetfactory/templates/meets/event_profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}
<table>
    <tr><td>Название</td><td>{{e.name}}</td></tr>
    <tr><td>Время начала</td><td>{{e.begin_date|date:"l, d F, H:i"}}</td></tr>
    <tr><td>Время окончания</td><td>{{e.end_date|date:"l, d F, H:i"}}</td></tr>
    <tr><td>Количество человек</td><td>Не менее {{e.low_people_count}}, не более {{e.high_people_count}}</td></tr>
    <tr><td>Категория</td><td>{{e.category}}</td></tr>
    <tr><td>Теги</td><td>{{tags}}</td></tr>
</table>
{%if user_in %}
Вы в тусовке
{%elif not request.user%}
Залогиньтесь, чтобы присоединиться
{%else%}
<form id=event_form action="{% url 'meetfactory:add' %}" method="post"> {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    <input type="submit" value="Присоединиться" />
</form>
{%endif%}
{% endblock %}

meetfactory/templates/meets/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}

<div class = "search"><form method="get" action="{% url 'meetfactory:index' %}">
        <input class = "search_in" name="q" type = "text" placeholder = "Введите поисковый запрос" value="{{q}}"/>
        <button type = submit>Искать!</button>
        <input type="checkbox" name = "nq" {%if G.nq%}checked{%endif%}>Название
        <input type="checkbox" name = "tq" {%if G.t%}checked{%endif%}>Теги
        <input type="checkbox" name = "dq" {%if G.dq%}checked{%endif%}>Описание
        <input type="checkbox" name = "lq" {%if G.lq%}checked{%endif%}>Карта

    </form></div>
	<div class = "category">
		<ul class = "ul_list">
            {% for c in categories %}
            <li onclick="window.location.href = '?category={{c.pk}}'">{{c}}</li>
            {% endfor %}
		</ul>
	</div>
	<div class = "list_list">
        {%if el%}
        <a href = "{%url 'meetfactory:event_create'%}">Нажмите, чтобы создать событие</a>
		<table class = "u_list">
        <thead>
            <tr style = "border-bottom: 1px solid black;">
                <td>Название</td>
                <td>Количество человек</td>
                <td>Начало</td>
                <td>Конец</td>
                <td>Организатор</td>
                <td>Описание</td>
                <td>Теги</td>
                <td>Карта</td>
            </tr>
        </thead>

        <tbody>
        {% for e in el %}
            <tr class = "ul_list_li">
                <td onclick = "window.location.href = 'events?id={{e.id}}'">
                    <a href = "/">
                        {{e.name}}
                    </a>
                </td>
                    <td onclick = "window.location.href = 'events?id={{e.id}}'">{{ e.low_people_count }}/{{ e.high_people_count }}</td>
                    <td onclick = "window.location.href = 'events?id={{e.id}}'">{{ e.begin_date }}</td>
                    <td onclick = "window.location.href = 'events?id={{e.id}}'">{{ e.end_date }}</td>
                    <td onclick = "window.location.href = 'events?id={{e.id}}'">{{ e.creator.first_name }} {{ e.creator.last_name}}</td>
                    <td onclick = "window.location.href = 'events?id={{e.id}}'">{{ e.desc }}</td>
                <td onclick = "window.location.href = 'events?id={{e.id}}'">
                    {% for t in e.tags.all%}
                        #{{t.name}}
                    {% endfor %}
                </td>
                <td onclick = "window.location.href = 'events?id={{e.id}}'">{{e.location}}</td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
        {%else%}
        Событий нет! {%if cat%}Выберите другую категорию
        {%else%}Вы можете <a href = "{%url 'meetfactory:event_create'%}">создать своё</a>{%endif%}
        {%endif%}


	</div>
	
<script type="text/javascript" src = "{% static 'meets/js/functions.js' %}"></script>
<script type="text/javascript" src = "{% static 'meets/js/map.js' %}"></script>

{% endblock %}

meetfactory/templates/meets/profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}
<div class = "wrapper">
	<div class = "head_title"><h3>Meet Factory</h3></div>
	<div class = "content">
		<div class = "avatar"><img src="{{ u.userpic }}" ></div>
		<div class = "info">
			<p class = "title_profile">Профиль</p>
			<p>Имя<span class = "field name">{{u.first_name}}</span></p>
			<p>Фамилия<span class = "field surname">{{u.last_name}}</span></p>
			<p>Дата рождения<span class = "field birthday">13 мая</span></p>
			<p>Родной город<span class = "field city">Владивосток</span></p>
			</div>
	</div>
</div>
<footer><a href="{% url 'meetfactory:profile' %}">Профиль</a>
	<a class = "create_footer" href="{% url 'meetfactory:event_create'%}">Создать событие</a>
</footer>

{% endblock %}